spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
    url: jdbc:mysql://localhost:3306/j106?useSSL=false&serverTimezone=Asia/Seoul
    username: user01
    password: user01 
  session:
    store-type: REDIS
  redis:
    host: localhost
    port: 6379    
logging:
  level:
    root: info
    shutup.code.j006: debug
