spring:
  db1:
    datasource:
      jdbc-url: jdbc:mariadb://localhost:13306/j108
      driver-class-name: org.mariadb.jdbc.Driver
      username: user01
      password: user01
  db2:
    datasource:
      jdbc-url: jdbc:mariadb://localhost:23306/j108
      driver-class-name: org.mariadb.jdbc.Driver
      username: user01
      password: user01
